version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: "@top-gg/sdk"
    versions:
    - 3.1.0
  - dependency-name: mathjs
    versions:
    - 9.3.2
  - dependency-name: discord.js
    versions:
    - 12.5.2
  - dependency-name: string-progressbar
    versions:
    - 1.0.3
